---
title: Análise de Sensores IoTs - Veracel
description: Análise de desempenho de dendrômetros IoTs para Veracel
author: 
  - name: Equipe de Sustentação
    affiliation: Treevia Forest Technologies
date: last-modified
title-block-banner: true
title-block-banner-color: "#3D7A43"
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    theme: cosmo
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Sumário
    toc-depth: 2
css: styles.css
execute: 
  echo: false
  warning: false
lang: "pt-br"
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(sf)
library(leaflet)
library(forecast)
library(plotly)
library(gt)
library(knitr)
library(htmltools)

source("utils.R")

options(scipen = 999)

data <- read_csv2("data/Inventario-SingleTrees -- Exportado - 24-07-2024 13-41.csv")

df <-
  data |> 
  mutate(across(c(Data_Plantio, Data_Medicao), dmy)) |> 
  filter(!Dap_Estimado)
```


## Distribuição espacial



```{r}
points <- 
  data |> 
  count(Estrato, Amostra, Coordenada_X, Coordenada_Y) |> 
  st_as_sf(coords = c("Coordenada_X", "Coordenada_Y"))

labels <- sprintf(
  "Estrato: %s <br/> Amostra: %s <br/>X: %f<br/>Y: %f",
  points$Estrato,
  points$Amostra,
  st_coordinates(points$geometry)[, 1],
  st_coordinates(points$geometry)[, 2]
) |> lapply(htmltools::HTML)

leaflet(points) |> 
  addProviderTiles("Esri.WorldImagery") |> 
  addMarkers(label = labels)
```

## Periodicidade

:::{.column-page}
:::{.panel-tabset}

```{r results='asis'}
#| warning: false
#| 

estratos <- unique(df$Estrato)

for(i in estratos) {
  cat("##",i, "\n\n\n")
  
  print(tagList(ggplotly(plot_estratos(df, i), tooltip = "text")))
  
  cat("\n\n")
}
```


<!-- ```{r} -->
<!-- #| warning: false -->
<!-- #| output: asis -->


<!-- estratos <- unique(df$Estrato) -->

<!-- cat("##", estratos[1], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[1]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[2], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[2]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[3], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[3]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[4], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[4]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[5], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[5]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[6], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[6]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[7], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[7]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[8], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[8]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[9], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[9]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[10], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[10]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[11], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[11]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[12], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[12]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[13], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[13]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[14], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[14]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[15], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[15]), tooltip = "text")) -->
<!-- cat("\n\n") -->

<!-- cat("##", estratos[16], "\n\n\n") -->
<!-- tagList(ggplotly(plot_estratos(df, estratos[16]), tooltip = "text")) -->
<!-- cat("\n\n") -->
<!-- ``` -->

:::
:::

## Datas erradas
:::{.column-body-outset}
```{r}
df |>
  filter(year(Data_Medicao) != 2024) |>
  select(Fazenda,
         Estrato,
         Talhao,
         Data_Medicao,
         Data_Plantio,
         Amostra,
         MAC,
         `DAP (cm)`) |>
  DT::datatable()
```
:::

## Outliers e Falhas

:::{.column-body-outset}

```{r}
#| warning: false

gaps <-
  df |> 
  filter(year(Data_Medicao) == 2024) |> 
  group_by(Estrato, Amostra) |> 
  arrange(Data_Medicao) |> 
  mutate(gap = as.numeric(Data_Medicao - lag(Data_Medicao)),
         is.gap = if_else(gap >= 9, T, F)) |> 
  summarise(gaps = sum(is.gap, na.rm = T))

liers <-
  df |>
  filter(year(Data_Medicao) == 2024) |>
  group_by(Estrato, Amostra) |>
  arrange(`DAP (cm)`) |>
  summarise(nliers = length(tsoutliers(`DAP (cm)`)$index)) |>
  ungroup()

full_join(liers, gaps, by = c("Estrato" = "Estrato", "Amostra" = "Amostra")) |> 
  rename("N° de Outliers" = nliers, "N° de Gaps" = gaps) |> 
  DT::datatable()
```

:::

::: {.column-body-outset}

```{r}
idades <-   
  df |> 
  filter(year(Data_Medicao) == 2024) |> 
  group_by(Estrato, Amostra, MAC) |> 
  summarise(idade = as.numeric(max(Data_Medicao) - min(Data_Medicao)))

dens <-
  ggplot(idades) +
  geom_density(
    fill = "green",
    color = "darkgreen",
    alpha = 0.25,
    aes(
      x = idade,
      y = after_stat(density),
      text = sprintf("Densidade: %.2f%%<br>Idade: %.2f",
                     after_stat(density) * 100, x)
    )
  ) +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(x = "Tempo de operação", y = "Densidade")

dens_ly <- ggplotly(dens, tooltip = "text")

idades_med <-
  idades |>
  ungroup() |>
  group_by(Estrato) |>
  summarise(mean = mean(idade),
            n_devc = ordered(n(), levels = c(9, 10, 11))) |>
  ggplot(aes(mean, Estrato)) +
  geom_col(
    alpha = 0.75,
    fill = "darkgreen",
    aes(text = sprintf("N° de Sensores: %s<br>Tempo médio: %.2f dias", 
                       n_devc, mean))
  ) +
  theme_minimal() +
  labs(x = "Dias", y = NULL, fill = "N° de Sensores")

idade_ly <- ggplotly(idades_med, tooltip = "text")

subplot(idade_ly, dens_ly, nrows = 1, margin = 0.07)
```
:::
